export const TEMPLATES = [
  {
    id: 'apex-pro',
    name: 'Apex Pro',
    ats: 97,
    tier: 'premium',      // 'free' | 'premium'
    category: ['all', 'professional', 'modern'],
    description: 'Modern 2-column ATS friendly template',
    bestFor: 'General professional',
    layout: 'two-column',
    accentColor: '#6C47FF',
  },
  {
    id: 'vertex-pro',
    name: 'Vertex Pro',
    ats: 95,
    tier: 'premium',
    category: ['all', 'professional'],
    description: 'Clean and modern professional template',
    bestFor: 'Product / design roles',
    layout: 'sidebar',
    accentColor: '#6C47FF',
  },
  {
    id: 'momentum',
    name: 'Momentum',
    ats: 94,
    tier: 'free',
    category: ['all', 'creative', 'modern'],
    description: 'Creative yet professional layout',
    bestFor: 'Creative professionals',
    layout: 'accent-header',
    accentColor: '#6C47FF',
  },
  {
    id: 'zenith',
    name: 'Zenith',
    ats: 92,
    tier: 'free',
    category: ['all', 'professional'],
    description: 'Minimal and elegant single column',
    bestFor: 'Any industry',
    layout: 'single-column',
    accentColor: '#333333',
  },
  {
    id: 'ascend',
    name: 'Ascend',
    ats: 91,
    tier: 'premium',
    category: ['all', 'tech'],
    description: 'Perfect for tech and developer roles',
    bestFor: 'Engineering / tech',
    layout: 'dark-header',
    accentColor: '#A78BFA',
  },
  {
    id: 'elite',
    name: 'Elite',
    ats: 90,
    tier: 'premium',
    category: ['all', 'professional'],
    description: 'Professional design for senior level roles',
    bestFor: 'Senior / executive',
    layout: 'accent-sidebar',
    accentColor: '#4ADE80',
  },
  {
    id: 'impact',
    name: 'Impact',
    ats: 89,
    tier: 'free',
    category: ['all', 'creative'],
    description: 'Bold design for maximum impact',
    bestFor: 'Sales / marketing',
    layout: 'bold-header',
    accentColor: '#F87171',
  },
];
